### ISSUE TITLE
need Licence info

### ISSUE THREAD

**Issue by javismiles** [zappar-xr/babylonjs-example-image-tracking-3d-model#1]
Dear friends

What is the licence of this code?
is it open source? free to use commercially?
could somebody post the licence info? :)
thank you so much :)

**Comment by nyan-left** [comment]
Hi @javismiles,


You can find out about our plans and licencing over on:

https://docs.zap.works/universal-ar/general/licensing/
https://zap.works/pricing/

**Comment by javismiles** [comment]
let's simplify please,
so it's not free open source, it's  a pay for service, ok got it, thanks ,
bye
